---
title: "TBC Diet Preference Analysis Figures"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include = F, warning = F, message = F}
# usethis::create_package('~/Dropbox/Dietary Pref 2019/TBCdietPref/TBCdietPrefv2')


rm(list=ls())


library(readxl)
library(dplyr)
library(RCurl)
library(httr)
library(lme4)
library(multcomp)
library(ggplot2)
library(cowplot)
library(MAGNAMWAR)
library(tidyr)
library(dunn.test)
library(rcompanion)
library(gridExtra)
library(learnr)

 ## function to combine data from multiple files for glucose and protein analysis
combine_files <- function(filepath1, sheet1, sheet1b, filepath2, sheet2, filepath3, sheet3) {
	
   # 	filepath1 = "Glucose_Protein_Values_JMC.xlsx"
   #   sheet1 = "Plate 1 Glucose"
   #   filepath2 = "plate1.xlsx"
   #   sheet2 = "Plate 1 - Sheet1"
   # 
  glucose_file <- read_xlsx(filepath1, sheet = sheet1, col_names = c(paste0("col", rep(1:12))),range = "B2:M9") %>% 
    gather() %>% 
    dplyr::rename(name = value) %>% 
    dplyr::select(name) %>% 
    cbind(read_xlsx(filepath2, sheet = sheet2, col_names = c(paste0("col", rep(1:12))),range = "c24:n31") %>% 
            gather() %>% 
            dplyr::rename(OD = value) %>% 
            dplyr::select(OD)
          )
  control_curve <- glucose_file %>% 
    filter(name%in%c("0",".1",".2",".4",".7","1")) %>% 
    mutate(name = as.numeric(as.character(name)))
  
  model <- lm(name ~ OD, control_curve)

  glucose_samples <- glucose_file %>% 
    filter(!is.na(name) & !name%in%c("0",".1",".2",".4",".7","1")) %>% 
    mutate(glucose = OD * model$coefficients[2] - model$coefficients[1]) %>%
    mutate(glucose_perfly = glucose * 5) %>%
    separate(col = name, into = c("plate","treatment","replicate"), sep = "-", remove = F)
  
   # filepath1 = "Glucose_Protein_Values.xlsx"
   # sheet1b = "Plate A Protein"
   # filepath3 = "PlateA.xlsx"
   # sheet3 = "Plate 1 - Sheet1"
	protein_file <- read_xlsx(filepath1, sheet = sheet1b, col_names = c(paste0("col", rep(1:12))),range = "B2:M9") %>% 
    gather() %>% 
    dplyr::rename(name = value) %>% 
    dplyr:: select(name) %>% 
    cbind(read_xlsx(filepath3, sheet = sheet3, col_names = c(paste0("col", rep(1:12))),range = "c24:n31") %>% 
            gather() %>% 
            dplyr::rename(OD = value) %>% 
            dplyr::select(OD)
          )

	model <- lm(name ~ OD, control_curve)

  protein_samples <- protein_file %>% 
    filter(!is.na(name) & !name%in%c("0","1","2","4","7","10")) %>% 
    mutate(protein = OD * model$coefficients[2] - model$coefficients[1]) %>% 
    mutate(protein = protein *2) %>%
    mutate(protein_perfly = protein * 2 * 5) %>%
  	dplyr::select(-OD)

  final_samples <- glucose_samples %>% inner_join(protein_samples, by = "name")
  
}

 ## function to calculate stats for sip duration
calc_feeding_time_stats <- function(gh_filepath,j=3) {
GET(gh_filepath, write_disk(tf <- tempfile(fileext = ".xls")))

aaa <- read_xls(tf, sheet = "NumberOfSips")
abb <- read_xls(tf, sheet = "Date")
aab <- read_xls(tf, sheet = "SipDurations")

ccc <- aaa
out_df <- data.frame(trt=character(), pref=numeric(),day=numeric(),time=numeric(),sip1 = numeric(), sip2 = numeric(), dieta=character(),dietb=character())

  for(i in 1:j) {
  	lacto_pref <- (ccc[,i]/(ccc[,(j+i)]+ccc[,i]))
  	lp2 <- cbind(lacto_pref,abb[,(i)], aab[,i],aab[,(i+j)],aaa[,i],aaa[,(j+i)])
  	lp3 <- lp2[(!is.na(lp2[,c(1)]) & lp2[,c(1)]!=-1 & !is.na(lp2[,c(3)]) & lp2[,c(3)]!=-1 & !is.na(lp2[,c(4)]) & lp2[,c(4)]!=-1),]
  	lp4 <- data.frame(lp3) %>% mutate(trt=paste0(colnames(ccc[i]),"_",colnames(ccc[i+j])), pref=lp3[,1], day=lp3[,2], time1=lp3[,3], time2 =lp3[,4],dieta=lp3[,5], dietb = lp3[,6], ) %>% dplyr::select(trt,pref,day,time = time1, sip1=dieta, sip2 = dietb, dieta=time1, dietb=time2) 
  	out_df <- rbind(out_df,lp4)
  }
  
  head(out_df)
  pref_data <- out_df %>% 
  	mutate(trt=gsub(pattern = " 10Y10G", replacement = "",x = trt,perl = T)) %>% 
  	mutate(trt=gsub(pattern = " 10Y7.5G", replacement = "",x = trt,perl = T)) %>%
  	mutate(trt=factor(trt)) %>%
  	filter(sip1<1000 & sip2<1000) %>%

  #	filter(dieta<200 & dietb<200) %>%
    mutate(total = dieta+dietb) %>%
  	droplevels() %>%
    reshape2::melt(measure.vars = c("dieta", "dietb"),variable.name = "time_consuming_diet")
  head(pref_data)
  
  pref_data$trt2 <- factor(pref_data$trt, labels = c("At","Ax","Lb"))
  pref_data$trt2 <- factor(pref_data$trt2, levels = c("Ax","At","Lb"))
  table(pref_data$trt2)
  pref_data$tt <- with(pref_data, interaction(trt2, time_consuming_diet))
  print(table(pref_data$tt))
  kwtest <- kruskal.test(pref_data$value ~ pref_data$tt)
  print(kwtest)

  if (kwtest$p.value < 0.05) {
    efg <- dunn.test(pref_data$value, pref_data$tt, method = "bh", table = F, kw=F)
    ghi <- cldList(comparison = efg$comparisons, p.value = efg$P.adjusted, threshold = 0.05)
    diff_codes <- as.character(unlist(ghi$Letter))
  } else {
    diff_codes <- c(rep("a",6))
  }
    
  pd3e <- pref_data %>%
    group_by(tt) %>%
    summarize(mean = mean(value), sem= sd(value)/sqrt(dplyr::n())) %>%
    ungroup()
  colors2 <- c("gray","gray","red","red","blue","blue")
  
  head(pd3e)
  
  pd3e$abc2.x <- plyr::revalue(pd3e$tt, c("Ax.dieta" = "Ax control","At.dieta" = "At control", "Lb.dieta" = "Lb control","Ax.dietb" = "Ax trial", "At.dietb" = "At trial", "Lb.dietb" = "Lb trial"))
  pd3e$abc2.x <- factor(pd3e$abc2.x, levels = c("Ax control","Ax trial","At control", "At trial", "Lb control", "Lb trial"))
  
  plot_text_size = 3
  p25g100y <- ggplot(pd3e, aes( x=abc2.x, y = mean,fill = abc2.x)) +
  	geom_bar(stat="identity",size=plot_text_size*1) +
    scale_color_manual(values = colors2) +
  	scale_fill_manual(name="Legend",values=colors2) +
  	scale_y_continuous(limits = c(0,.3))+
  	theme_cowplot() +
#  	theme(text = element_text(size=plot_text_size), axis.title = element_blank(), legend.position = "none", axis.line = element_line(size = 0.2), axis.text = element_text(angle = 45), axis.ticks = element_blank()) +
    	theme(text = element_text(size=plot_text_size), axis.title = element_blank(), legend.position = "none", axis.line = element_line(size = 0.2), axis.text = element_blank(), axis.ticks = element_blank()) +
  	geom_errorbar(col = "black", aes(ymax =mean+sem, ymin = mean-sem), width=0.25, size=.25) +
  #	geom_hline(yintercept = 0.5, linetype="dashed") +
 	geom_text(aes(label=c(diff_codes[c(3,1,5,4,2,6)]), y=mean + sem + .02), size=plot_text_size/2)
  return(p25g100y)
}


```

## Figure S1 {.tabset}

### plot 100g100y
```{r fig1100g100y, warning = F, message = F, eval = T, exercise.timelimit = 10000}

GET("http://github.com/johnchaston/TBCdietPref/blob/master/files/DataInExcelFormat%20100.100%20vs%20100.00%20+Date.xls?raw=true", write_disk(tf <- tempfile(fileext = ".xls")))

aaa <- read_xls(tf, sheet = "NumberOfSips")
abb <- read_xls(tf, sheet = "Date")
aab <- read_xls(tf, sheet = "Date")
ccc <- aaa

out_df <- data.frame(trt=character(), pref=numeric(),day=numeric(),time=numeric(),dieta=character(),dietb=character())
j=3
for(i in 1:j) {
	lacto_pref <- (ccc[,i]/(ccc[,(j+i)]+ccc[,i]))
	lp2 <- cbind(lacto_pref,abb[,(i)], aab[,i],aaa[,i],aaa[,(j+i)])
	lp3 <- lp2[(!is.na(lp2[,1]) & lp2[,1]!=-1),]
	lp4 <- data.frame(lp3) %>% mutate(trt=paste0(colnames(ccc[i]),"_",colnames(ccc[i+j])), pref=lp3[,1], day=lp3[,2], time=lp3[,3],dieta=lp3[,4],dietb=lp3[,5]) %>% dplyr::select(trt,pref,day,dieta,dietb)
	out_df <- rbind(out_df,lp4)
}

pref_data <- out_df %>% 
	mutate(trt=gsub(pattern = " 10Y10G", replacement = "",x = trt,perl = T)) %>% 
	mutate(trt=gsub(pattern = " 10Y7.5G", replacement = "",x = trt,perl = T)) %>%
	mutate(trt=factor(trt)) %>%
	filter(dieta<1000 & dietb<1000) %>%
	droplevels()

pd2 <- pref_data

pd2$day2 <- as.factor(as.character(pd2$day))
pd2$trt <- as.factor(as.character(pd2$trt))

abc <- glmer(cbind(dieta,dietb) ~ trt + (1|day2), data=pd2, family = "binomial")
cat("Statistics summary")
summary(abc)
abc1 <- glht(abc, mcp(trt='Tukey'))
abc2 <- cld(abc1)
pd3e <- data.frame(abc2$lp, abc2$x) %>% group_by(abc2.x) %>% dplyr::summarize(mean = mean(abc2.lp), sem=sd(abc2.lp)/sqrt(sum(abc2.lp<2)))
colors2 <- c("gray","red","blue")

pd3e$abc2.x <- plyr::revalue(pd3e$abc2.x, c("aceto 100g_aceto 100" = "At","axenic 100g_axenic 100" = "Ax","lacto 100g_lacto 100" = "Lb"))

pd3e$abc2.x <- factor(pd3e$abc2.x, levels = c("Ax","At","Lb"))

plot_text_size = 3
p100g100y <- ggplot(pd3e, aes(x = abc2.x, xend=abc2.x, y=c(rep(0.5,length(table(list(abc2.x))))), yend=mean, col = abc2.x)) + 
	geom_segment(stat="identity",size=plot_text_size*1.75) + 
  scale_color_manual(values = colors2) +
	scale_fill_manual(name="Legend",values=colors2) +
	scale_y_continuous(limits = c(0,1))+
	theme_cowplot() + 
	theme(text = element_text(size=plot_text_size), axis.title = element_blank(), axis.text = element_blank(), legend.position = "none", axis.ticks = element_blank(), axis.line = element_line(size = 0.2)) +
	geom_errorbar(col = "black", ymax =pd3e$mean+pd3e$sem, ymin = pd3e$mean-pd3e$sem, width=0.25, size=.25) +
	geom_hline(yintercept = 0.5, linetype="dashed") +
 	geom_text(aes(label=c("a","b","c"), y=.75), size=plot_text_size) + coord_flip()
p100g100y
#ggsave(h=2,w=3.5,"100G100Y.png")

```
